-- MySQL Script generated by MySQL Workbench
-- Thu Aug 28 10:50:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema grovy_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grovy_db` ;

-- -----------------------------------------------------
-- Schema grovy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grovy_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `grovy_db` ;

-- -----------------------------------------------------
-- Table `grovy_db`.`profissionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grovy_db`.`profissionais` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `confirmação de senha` VARCHAR(45) NOT NULL,
  `confirmação de profissão` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grovy_db`.`usuários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grovy_db`.`usuários` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `confirmação de senha` VARCHAR(45) NOT NULL,
  `idade` INT(2) NOT NULL,
  `telefone` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
